# Generated by Django 4.0.6 on 2022-07-27 11:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_alter_vendor_exe_contact_phone_alter_vendor_logo_and_more'),
        ('profiles', '0002_alter_profile_full_name'),
        ('contracts', '0006_alter_contract_created_by'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='amount_outstanding',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Amount Outstanding'),
        ),
        migrations.AddField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='service_provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='vendors.vendor', verbose_name='Service Provider'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress - On track', 'In Progress - On track'), ('In Progress - Delayed', 'In Progress- Delayed'), ('Stopped', 'Stopped'), ('Completed', 'Completed')], default='Not Started', max_length=150),
        ),
        migrations.AddField(
            model_name='project',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='Total Project Value'),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_role', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress - On track', 'In Progress - On track'), ('In Progress - Delayed', 'In Progress- Delayed'), ('Stopped', 'Stopped'), ('Completed', 'Completed')], default='Project Manager', max_length=150, verbose_name='Project Role')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profiles', to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='milestone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.deliverable', verbose_name='Milestone'),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='projects.team'),
        ),
    ]
