# Generated by Django 4.0.6 on 2022-07-27 11:52

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_created_by'),
        ('vendors', '0002_alter_vendor_exe_contact_phone_alter_vendor_logo_and_more'),
        ('projects', '0002_deliverable_project_amount_outstanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='amount_outstanding',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=10, null=True, verbose_name='Amount Outstanding'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='project',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='projects.deliverable', verbose_name='Milestone'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='vendors.vendor', verbose_name='Service Provider'),
        ),
        migrations.AlterField(
            model_name='project',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='projects.team'),
        ),
    ]
