# Generated by Django 4.0.6 on 2022-07-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_amount_outstanding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project_role',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Technical Lead', 'Technical Lead'), ('Technical Support', 'Technical Support'), ('User Support', 'User Suport'), ('Business User', 'Business User')], default='Project Manager', max_length=150, verbose_name='Project Role'),
        ),
    ]
