# Generated by Django 4.0.6 on 2022-07-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_team_project_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('On track', 'On track'), ('Delayed', 'Delayed'), ('Stopped', 'Stopped'), ('Completed', 'Completed')], default='Not Started', max_length=150),
        ),
    ]
