# Generated by Django 4.0.6 on 2022-07-14 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='duration',
        ),
    ]
