# Generated by Django 4.0.6 on 2022-07-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_remove_contract_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_id',
            field=models.CharField(max_length=100, verbose_name='Contract ID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='responsible_unit',
            field=models.CharField(max_length=300, verbose_name='Responsible Unit'),
        ),
    ]
