# Generated by Django 4.0.6 on 2022-07-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_alter_contract_contract_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('Active - Ok', 'Active - Ok'), ('Active - Alert 1', 'Active-Alert 1'), ('Active - Alert 2', 'Active - Alert 2'), ('Expired', 'Expired')], default='Active - Ok', max_length=300),
        ),
    ]
