# Generated by Django 4.0.6 on 2022-07-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0004_alter_contract_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='status',
            field=models.CharField(default='Active - Ok', editable=False, max_length=300),
        ),
    ]
