# Generated by Django 4.0.6 on 2022-07-29 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_num',
        ),
    ]
