# Generated by Django 4.0.6 on 2022-07-12 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='exe_contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Executive Contact Phone'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='company_logos/%Y'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='postal_address',
            field=models.CharField(max_length=300, verbose_name='Postal Address'),
        ),
    ]
