# Generated by Django 4.0.6 on 2022-07-21 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_alter_contract_created_by'),
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='license',
            old_name='inception_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='license',
            name='agreement_term',
        ),
        migrations.RemoveField(
            model_name='license',
            name='num_system_users',
        ),
        migrations.RemoveField(
            model_name='license',
            name='renewal_status_ind',
        ),
        migrations.AddField(
            model_name='license',
            name='num_admin_users',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Number of Admin Users'),
        ),
        migrations.AddField(
            model_name='license',
            name='renewal_term',
            field=models.CharField(choices=[(None, 'Select agreement term'), ('Annual Renewal', 'Annual Renewal'), ('Once-Off', 'Once-Off'), ('Contract Term Linked', 'Contract Term Linked'), ('Pepertual', 'Pepertual')], default='Annual Renewal', max_length=250, verbose_name='Agreement Term'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='license',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract', to='contracts.contract'),
        ),
        migrations.AlterField(
            model_name='license',
            name='next_renewal_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='Next Renewal Date'),
        ),
        migrations.AlterField(
            model_name='license',
            name='renewal_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('Supplier Invitation', 'Supplier Invitation'), ('Purchase Request', 'Purchase Request'), ('Purchase Order', 'Purchase Order'), ('Invoice', 'Invoice'), ('Paid', 'Paid')], default='Not Started', max_length=250, verbose_name='Renewal Status'),
        ),
        migrations.AlterField(
            model_name='license',
            name='software_category',
            field=models.CharField(choices=[(None, 'Select software category'), ('Productivity', 'Productivity'), ('Enterprise Resource Planning', 'Enterprise Resource Planning'), ('Learning Management System', 'Learning Management System'), ('Operating System', 'Operating System'), ('Database Management System', 'Database Management System'), ('Business Intelligence', 'Business Intelligence'), ('Data & Statistical Analytics', 'Data & Statistical Analytics'), ('Network Management', 'Network Management'), ('IT Service Management', 'IT Service Management'), ('Communication', 'Communication'), ('Collaboration', 'Collaboration'), ('Business Application', 'Business Application'), ('Academic Specialist Software', 'Academic Specialist Software')], max_length=250, verbose_name='Software Category'),
        ),
        migrations.AlterField(
            model_name='license',
            name='user_base',
            field=models.CharField(choices=[(None, 'Select user base'), ('Students', 'Students'), ('Academics', 'Academics'), ('Academics & Students', 'Academics & Students'), ('Admin Staff', 'Admin Staff'), ('Admin Staff & Students', 'Admin Staff & Students'), ('All Staff', 'All Staff'), ('All Staff & Students', 'All Staff & Students'), ('Academics Specialist', 'Academics Specialist'), ('ICT Staff', 'ICT Staff')], max_length=250, verbose_name='User Base'),
        ),
    ]
