# Generated by Django 4.0.6 on 2022-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0002_rename_inception_date_license_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='renewal_term',
            field=models.CharField(choices=[('Annual Renewal', 'Annual Renewal'), ('Once-Off', 'Once-Off'), ('Contract Term Linked', 'Contract Term Linked'), ('Pepertual', 'Pepertual')], max_length=250, verbose_name='Renewal Term'),
        ),
    ]
